/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package product_management;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.lang.Object;
import java.util.ResourceBundle;
import java.nio.charset.Charset;
import static java.nio.charset.StandardCharsets.ISO_8859_1;
import static java.nio.charset.StandardCharsets.UTF_8;
/**
 *
 * @author PHUC
 */
public class Ncc extends javax.swing.JFrame {

    /**
     * Creates new form Ncc
     */
    public Ncc() {
        initComponents();
        this.setLocationRelativeTo(null);
        setButton(true);
        Show_Ncc_In_JTable();
    }
String ImgPathncc = null;
    int pos = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idncc = new javax.swing.JTextField();
        txt_namencc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_ncc = new javax.swing.JTable();
        Btn_Choose_Imagencc = new javax.swing.JButton();
        lbl_imagencc = new javax.swing.JLabel();
        Btn_Insertncc = new javax.swing.JButton();
        Btn_Updatencc = new javax.swing.JButton();
        Btn_Deletencc = new javax.swing.JButton();
        Btn_Savencc = new javax.swing.JButton();
        BtnRefreshncc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_idncc.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txt_idncc.setEnabled(false);

        txt_namencc.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setText("Nhà cung cấp");

        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(292, 292, 292)
                .addComponent(BtnMenu))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnMenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JTable_ncc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên"
            }
        ));
        JTable_ncc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_nccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_ncc);

        Btn_Choose_Imagencc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Btn_Choose_Imagencc.setText("Chọn hình");
        Btn_Choose_Imagencc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Choose_ImagenccActionPerformed(evt);
            }
        });

        lbl_imagencc.setOpaque(true);

        Btn_Insertncc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btn_Insertncc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        Btn_Insertncc.setText("Thêm");
        Btn_Insertncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertnccActionPerformed(evt);
            }
        });

        Btn_Updatencc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btn_Updatencc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        Btn_Updatencc.setText("Cập nhật");
        Btn_Updatencc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdatenccActionPerformed(evt);
            }
        });

        Btn_Deletencc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btn_Deletencc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        Btn_Deletencc.setText("Xóa");
        Btn_Deletencc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeletenccActionPerformed(evt);
            }
        });

        Btn_Savencc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btn_Savencc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save-file-option.png"))); // NOI18N
        Btn_Savencc.setText("Lưu");
        Btn_Savencc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SavenccActionPerformed(evt);
            }
        });

        BtnRefreshncc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh (1).png"))); // NOI18N
        BtnRefreshncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshnccActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setText("ID Nhà cung cấp");

        jLabel3.setText("Tên");

        jLabel4.setText("Hình");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addComponent(lbl_imagencc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addContainerGap(677, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(Btn_Insertncc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Updatencc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Deletencc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Savencc))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Btn_Choose_Imagencc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_idncc)
                                        .addComponent(txt_namencc, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(414, 414, 414)
                                    .addComponent(BtnRefreshncc)
                                    .addGap(376, 376, 376))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(479, 479, 479)
                    .addComponent(jLabel1)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_imagencc, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_idncc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_namencc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Choose_Imagencc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Insertncc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Updatencc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Deletencc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Savencc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnRefreshncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(jLabel1)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void setButton(boolean a)
    {
        //Vô hiệu hoặc có hiệu lực cho các JButton
        this.Btn_Insertncc.setEnabled(a);
        this.Btn_Deletencc.setEnabled(a);
        this.Btn_Updatencc.setEnabled(a);
        this.Btn_Savencc.setEnabled(!a);
        
    }
  public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/java_db","root","");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
     // Hàm kiểm tra giá trị của các textbox
   
 public ArrayList<Nhacc> getnccList()
    {
            ArrayList<Nhacc> nccList  = new ArrayList<Nhacc>();
            Connection con = getConnection();
            String query = "SELECT * FROM ncc";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Nhacc nhacc;
            
            while(rs.next())
            {
                nhacc = new Nhacc(rs.getInt("idNcc"),rs.getString("nameNcc"),rs.getBytes("imageNcc"));
                nccList.add(nhacc);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return nccList; 
                
    }
 public void Show_Ncc_In_JTable()
    {
        ArrayList<Nhacc> list = getnccList();
        DefaultTableModel model = (DefaultTableModel)JTable_ncc.getModel();
        // clear jtable content
       
        model.setRowCount(0);
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getIdncc();
            row[1] = list.get(i).getNamencc();
//            byte[] ptext = list.get(i).getName().getBytes(ISO_8859_1); 
//            row[1] = new String(ptext, UTF_8); 
           
            
            model.addRow(row);
        }
    
    }
    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        Menu_Form form = new Menu_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        // Đóng form hiện tại (Main_Window) mở form Menu (Menu_Form)
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void JTable_nccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_nccMouseClicked
        // TODO add your handling code here:
        setButton(true);
        int index = JTable_ncc.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_JTable_nccMouseClicked
 public void ShowItem(int index)
    {
            txt_idncc.setText(Integer.toString((int) getnccList().get(index).getIdncc()));
            txt_namencc.setText((String) getnccList().get(index).getNamencc());
           
        
        
        lbl_imagencc.setIcon(ResizeImage(null, getnccList().get(index).getImagencc()));
    }
 
    
 
    
 public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_imagencc.getWidth(), lbl_imagencc.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
        
    }
    private void Btn_Choose_ImagenccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Choose_ImagenccActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_imagencc.setIcon(ResizeImage(path, null));
            ImgPathncc = path;
        }
        else{
            System.out.println("Không có ảnh được chọn");
        }
    }//GEN-LAST:event_Btn_Choose_ImagenccActionPerformed
  public void setKhoa(boolean a)
    {
        //Khóa hoặc mở khóa cho các JTextField
        this.txt_namencc.setEnabled(!a);
       
        
        this.Btn_Choose_Imagencc.setEnabled(!a);
    }
  
  
  public void setNull()
    {
        this.txt_idncc.setText(null);
        this.txt_namencc.setText(null);
       
        this.lbl_imagencc.setIcon(null);
        this.txt_namencc.requestFocus();
    }
    private void Btn_InsertnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertnccActionPerformed
        // TODO add your handling code here:
        //Xóa TextField
          if(checkInputs() && ImgPathncc != null)
        {
            try {
                 Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO ncc(nameNcc,imageNcc)"
                        + "values(?,?) ");
                ps.setString(1, txt_namencc.getText());
            
               
               // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                
             
               
                InputStream img = new FileInputStream(new File(ImgPathncc));
                ps.setBlob(2, img);
                ps.executeUpdate();
                Show_Ncc_In_JTable();
               
                JOptionPane.showMessageDialog(null, "Data Inserted");
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Field Are Empty");
    }//GEN-LAST:event_Btn_InsertnccActionPerformed
    }
public boolean checkInputs()
    {
        if(
              txt_namencc.getText() == null
          
          )
        {
            return false;
        } return true; 
          
    }
    private void Btn_UpdatenccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdatenccActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && txt_idncc.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = getConnection();

            //update mà không cần image
            if(ImgPathncc == null)
            {
                try {
                    UpdateQuery = "UPDATE ncc SET nameNcc = ?  WHERE idNcc = ?";
                    ps = con.prepareStatement(UpdateQuery);

                    ps.setString(1, txt_namencc.getText());
                    

                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                   

                   

                    ps.setInt(2, Integer.parseInt(txt_idncc.getText()));

                    ps.executeUpdate();
                    Show_Ncc_In_JTable();
                    JOptionPane.showMessageDialog(null, "Đã cập nhật sản phẩm");

                } catch (SQLException ex) {
                    Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            // update có image
            else{
                try{
                    InputStream img = new FileInputStream(new File(ImgPathncc));

                    UpdateQuery = "UPDATE ncc SET nameNcc = ?, imageNcc = ? WHERE idNcc = ?";

                    ps = con.prepareStatement(UpdateQuery);

                    ps.setString(1, txt_namencc.getText());
                  

                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                   
                  

                    ps.setBlob(2, img);

                    ps.setInt(3, Integer.parseInt(txt_idncc.getText()));

                    ps.executeUpdate();
                    Show_Ncc_In_JTable();
                    JOptionPane.showMessageDialog(null, "Đã cập nhật sản phẩm");

                }catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Dữ liệu còn thiếu, vui lòng nhập thêm");
        }
    }//GEN-LAST:event_Btn_UpdatenccActionPerformed

    private void Btn_DeletenccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeletenccActionPerformed
        // TODO add your handling code here:
        String ten = txt_namencc.getText();
        if(!txt_idncc.getText().equals(""))
        {
            try {
                if (JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhà cung cấp "+ten+" không?","Thông báo", 2)==0){
                    Connection con = getConnection();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM ncc WHERE idNcc = ?");
                    int id = Integer.parseInt(txt_idncc.getText());
                    ps.setInt(1, id);
                    ps.executeUpdate();
                    Show_Ncc_In_JTable();
                    //Xóa dữ liệu trong TextField
                    setNull();
                }

            } catch (SQLException ex) {
                Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }

        }else{
            JOptionPane.showMessageDialog(null, "Chọn 1 sản phẩm để xóa","Thông báo", 1);
        }
    }//GEN-LAST:event_Btn_DeletenccActionPerformed

    private void Btn_SavenccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SavenccActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && ImgPathncc != null)
        {
            try {
                Connection con = getConnection();
                //                String query = "INSERT INTO products(name,price,add_date,image) values(N'"+ten+"','"+gia+"','"+addDate+"','"+img+"')" ;
                PreparedStatement ps = con.prepareStatement("INSERT INTO ncc(name,image)" + " values(?,?) ");
                //PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, txt_namencc.getText());
              

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
             

                InputStream img = new FileInputStream(new File(ImgPathncc));
                ps.setBlob(2, img);
                ps.executeUpdate();
                setNull();
                setButton(true);
                Show_Ncc_In_JTable();

                JOptionPane.showMessageDialog(null, "Dữ liệu đã được thêm");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Dữ liệu còn thiếu, vui lòng nhập thêm");
        }

        // only for test
        System.out.println("Name => "+txt_namencc.getText());
       ;
        System.out.println("Image => "+ImgPathncc);
    }//GEN-LAST:event_Btn_SavenccActionPerformed

    
    private void BtnRefreshnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshnccActionPerformed
        // TODO add your handling code here:
        Main_Window form = new Main_Window();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        // Đóng form hiện tại (Main_Window) mở form Menu (Menu_Form)
        this.dispose();
    }//GEN-LAST:event_BtnRefreshnccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ncc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ncc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ncc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ncc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Ncc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnRefreshncc;
    private javax.swing.JButton Btn_Choose_Imagencc;
    private javax.swing.JButton Btn_Deletencc;
    private javax.swing.JButton Btn_Insertncc;
    private javax.swing.JButton Btn_Savencc;
    private javax.swing.JButton Btn_Updatencc;
    private javax.swing.JTable JTable_ncc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_imagencc;
    private javax.swing.JTextField txt_idncc;
    private javax.swing.JTextField txt_namencc;
    // End of variables declaration//GEN-END:variables

    
}
